name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: "pnpm"
    - uses: pnpm/action-setup@v2
      with: 
        version: 9.12.2
    - name: Install dependencies
      run: pnpm install --prefer-offline --frozen-lockfile
    # - name: Install Playwright Browsers
    #   run: pnpx playwright install chromium
    - name: Run Playwright tests
      run: pnpm run ci
      env:
        NEXT_PUBLIC_APP_ID: registry
        NEXT_PUBLIC_APP_ENV: development
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MOBULA_API_KEY: ${{ secrets.MOBULA_API_KEY }}
        CRON_SECRET: ${{ secrets.CRON_SECRET }}
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}
        POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
        OFFICIAL_CFCE_API_KEY: ${{ secrets.OFFICIAL_CFCE_API_KEY }}
        CFCE_REGISTRY_API_KEY: ${{ secrets.CFCE_REGISTRY_API_KEY }}
        CFCE_REGISTRY_API_URL: http://localhost:3000/api
        XDC_WALLET_SECRET: ${{ secrets.XDC_WALLET_SECRET }}
        IPFS_API_KEY: ${{ secrets.IPFS_API_KEY }}
        IPFS_API_SECRET: ${{ secrets.IPFS_API_SECRET }}
        BLOB_READ_WRITE_TOKEN: ${{ secrets.BLOB_READ_WRITE_TOKEN }}
