import type { ChainConfig, ChainSlugs, Chains } from "@cfce/types"

const chainConfiguration: Chains = {
  arbitrum: {
    slug: "arbitrum",
    name: "Arbitrum",
    symbol: "ARB",
    logo: "arb.svg",
    icon: require("../assets/arb.svg").default,
    networks: {},
  },
  avalanche: {
    slug: "avalanche",
    name: "Avalanche",
    symbol: "AVAX",
    logo: "avax.svg",
    icon: require("../assets/avax.svg").default,
    networks: {},
  },
  base: {
    slug: "base",
    name: "Base",
    symbol: "BASE",
    logo: "base.svg",
    icon: require("../assets/base.svg").default,
    networks: {},
  },
  binance: {
    slug: "binance",
    name: "Binance",
    symbol: "BNB",
    logo: "bnb.svg",
    icon: require("../assets/bnb.svg").default,
    networks: {},
  },
  celo: {
    slug: "celo",
    name: "Celo",
    symbol: "CELO",
    logo: "celo.svg",
    icon: require("../assets/celo.svg").default,
    networks: {},
  },
  eos: {
    slug: "eos",
    name: "EOS",
    symbol: "EOS",
    logo: "eos.svg",
    icon: require("../assets/eos.svg").default,
    networks: {},
  },
  ethereum: {
    slug: "ethereum",
    name: "Ethereum",
    symbol: "ETH",
    logo: "eth.svg",
    icon: require("../assets/eth.svg").default,
    networks: {},
  },
  filecoin: {
    slug: "filecoin",
    name: "Filecoin",
    symbol: "FIL",
    logo: "fil.svg",
    icon: require("../assets/fil.svg").default,
    networks: {},
  },
  flare: {
    slug: "flare",
    name: "Flare",
    symbol: "FLR",
    logo: "flr.svg",
    icon: require("../assets/flr.svg").default,
    networks: {},
  },
  optimism: {
    slug: "optimism",
    name: "Optimism",
    symbol: "OP",
    logo: "op.svg",
    icon: require("../assets/op.svg").default,
    networks: {},
  },
  polygon: {
    slug: "polygon",
    name: "Polygon",
    symbol: "MATIC",
    logo: "matic.svg",
    icon: require("../assets/matic.svg").default,
    networks: {},
  },
  starknet: {
    slug: "starknet",
    name: "Starknet",
    symbol: "STRK",
    logo: "strk.svg",
    icon: require("../assets/strk.svg").default,
    networks: {},
  },
  stellar: {
    slug: "stellar",
    name: "Stellar",
    symbol: "XLM",
    logo: "xlm.svg",
    icon: require("../assets/xlm.svg").default,
    networks: {},
  },
  xinfin: {
    slug: "xinfin",
    name: "XDC",
    symbol: "XDC",
    logo: "xdc.svg",
    icon: require("../assets/xdc.svg").default,
    networks: {},
  },
  xrpl: {
    slug: "xrpl",
    name: "XRPL",
    symbol: "XRP",
    logo: "xrp.svg",
    icon: require("../assets/xrp.svg").default,
    networks: {},
  },
} as const

chainConfiguration.arbitrum.networks.mainnet = {
  id: 42161,
  name: "Arbitrum Mainnet",
  slug: "mainnet",
  symbol: "ARB",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://arbiscan.io",
  rpcUrl: "https://arb1.arbitrum.io/rpc",
  wssurl: "",
}
chainConfiguration.arbitrum.networks.testnet = {
  id: 421614,
  name: "Arbitrum Testnet",
  slug: "testnet",
  symbol: "ARB",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://sepolia.arbiscan.io",
  rpcUrl: "https://sepolia-rollup.arbitrum.io/rpc",
  wssurl: "",
}
chainConfiguration.avalanche.networks.mainnet = {
  id: 43114,
  name: "Avalanche Mainnet",
  slug: "mainnet",
  symbol: "AVAX",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://snowtrace.io",
  rpcUrl: "https://ethereum.publicnode.com",
  wssurl: "",
}
chainConfiguration.avalanche.networks.testnet = {
  id: 43113,
  name: "Avalanche Testnet",
  slug: "testnet",
  symbol: "AVAX",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://testnet.snowtrace.io",
  rpcUrl: "https://ethereum-goerli.publicnode.com",
  wssurl: "",
}
chainConfiguration.base.networks.mainnet = {
  id: 8453,
  name: "Base Mainnet",
  slug: "mainnet",
  symbol: "BASE",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://basescan.org",
  rpcUrl: "https://mainnet.base.org",
  wssurl: "",
}
chainConfiguration.base.networks.testnet = {
  id: 84532,
  name: "Base Testnet",
  slug: "testnet",
  symbol: "BASE",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://testnet.basescan.org",
  rpcUrl: "https://testnet.base.org",
  wssurl: "",
}
chainConfiguration.binance.networks.mainnet = {
  id: 56,
  name: "Binance Mainnet",
  slug: "mainnet",
  symbol: "BNB",
  decimals: 18,
  gasprice: "9000000000",
  explorer: "https://bscscan.com",
  rpcUrl: "https://bsc-dataseed.binance.org",
  wssurl: "",
}
chainConfiguration.binance.networks.testnet = {
  id: 97,
  name: "Binance Testnet",
  slug: "testnet",
  symbol: "BNB",
  decimals: 18,
  gasprice: "9000000000",
  explorer: "https://testnet.bscscan.com",
  rpcUrl: "https://data-seed-prebsc-1-s1.binance.org:8545",
  wssurl: "",
}
chainConfiguration.celo.networks.mainnet = {
  id: 42220,
  name: "Celo Mainnet",
  slug: "mainnet",
  symbol: "CELO",
  decimals: 18,
  gasprice: "10000000000",
  explorer: "https://explorer.celo.org",
  rpcUrl: "https://forno.celo.org",
  wssurl: "",
}
chainConfiguration.celo.networks.testnet = {
  id: 44787,
  name: "Celo Testnet",
  slug: "testnet",
  symbol: "CELO",
  decimals: 18,
  gasprice: "10000000000",
  explorer: "https://alfajores-blockscout.celo-testnet.org",
  rpcUrl: "https://alfajores-forno.celo-testnet.org",
  wssurl: "",
}
chainConfiguration.eos.networks.mainnet = {
  id: 17777,
  name: "EOS Mainnet",
  slug: "mainnet",
  symbol: "EOS",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://explorer.eos.io",
  rpcUrl: "https://api.eos.io",
  wssurl: "",
}
chainConfiguration.eos.networks.testnet = {
  id: 15557,
  name: "EOS Testnet Goerli",
  slug: "testnet",
  symbol: "EOS",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://explorer.testnet.eos.io",
  rpcUrl: "https://api.testnet.eos.io",
  wssurl: "",
}
chainConfiguration.ethereum.networks.mainnet = {
  id: 1,
  name: "Ethereum Mainnet",
  slug: "mainnet",
  symbol: "ETH",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://etherscan.io",
  rpcUrl: "https://ethereum.publicnode.com",
  wssurl: "",
}
chainConfiguration.ethereum.networks.testnet = {
  id: 5,
  name: "Ethereum Testnet",
  slug: "testnet",
  symbol: "ETH",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://goerli.etherscan.io",
  rpcUrl: "https://ethereum-goerli.publicnode.com",
  wssurl: "",
}
chainConfiguration.filecoin.networks.mainnet = {
  id: 31415790,
  name: "Filecoin Mainnet",
  slug: "mainnet",
  symbol: "FIL",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://filscan.io",
  rpcUrl: "https://api.node.glif.io",
  wssurl: "",
}
chainConfiguration.filecoin.networks.testnet = {
  id: 314159,
  name: "Filecoin Testnet",
  slug: "testnet",
  symbol: "FIL",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://calibration.filscan.io",
  rpcUrl: "https://api.calibration.node.glif.io",
  wssurl: "",
}
chainConfiguration.flare.networks.mainnet = {
  id: 14,
  name: "Flare Mainnet",
  slug: "mainnet",
  symbol: "FLR",
  decimals: 18,
  gasprice: "25000000000",
  explorer: "https://flare-explorer.flare.network",
  rpcUrl: "https://mainnet.flare.network",
  wssurl: "",
}
chainConfiguration.flare.networks.testnet = {
  id: 16,
  name: "Flare Testnet",
  slug: "testnet",
  symbol: "FLR",
  decimals: 18,
  gasprice: "25000000000",
  explorer: "https://coston-explorer.flare.network",
  rpcUrl: "https://coston-api.flare.network/ext/bc/C/rpc",
  wssurl: "",
}
chainConfiguration.optimism.networks.mainnet = {
  id: 10,
  name: "Optimism Mainnet",
  slug: "mainnet",
  symbol: "OP",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://goerli.etherscan.io",
  rpcUrl: "https://ethereum-goerli.publicnode.com",
  wssurl: "",
}
chainConfiguration.optimism.networks.testnet = {
  id: 5,
  name: "Optimism Testnet",
  slug: "testnet",
  symbol: "OP",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://goerli.etherscan.io",
  rpcUrl: "https://ethereum-goerli.publicnode.com",
  wssurl: "",
}
chainConfiguration.polygon.networks.mainnet = {
  id: 137,
  name: "Polygon Mainnet",
  slug: "mainnet",
  symbol: "MATIC",
  decimals: 18,
  gasprice: "20000000000",
  explorer: "https://polygonscan.com",
  rpcUrl: "https://ethereum.publicnode.com",
  wssurl: "",
}
chainConfiguration.polygon.networks.testnet = {
  id: 80001,
  name: "Polygon Testnet",
  slug: "testnet",
  symbol: "MATIC",
  decimals: 18,
  gasprice: "20000000000",
  explorer: "https://mumbai.polygonscan.com",
  rpcUrl: "https://ethereum-goerli.publicnode.com",
  wssurl: "",
}
chainConfiguration.starknet.networks.mainnet = {
  id: 0,
  name: "Starknet Mainnet",
  slug: "mainnet",
  symbol: "STRK",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://goerli.etherscan.io",
  rpcUrl:
    "https://starknet-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
  wssurl: "",
  tokens: {
    USDT: {
      contract:
        "0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8",
      name: "Tether USD",
      symbol: "USDT",
      decimals: 6,
      logo: "usdt.svg",
    },
    USDC: {
      contract:
        "0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8",
      name: "USD Coin",
      symbol: "USDC",
      decimals: 6,
      logo: "usdc.svg",
    },
  },
}
chainConfiguration.starknet.networks.testnet = {
  id: 0,
  name: "Starknet Testnet",
  slug: "testnet",
  symbol: "STRK",
  decimals: 18,
  gasprice: "250000000",
  explorer: "https://goerli.etherscan.io",
  rpcUrl:
    "https://starknet-goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
  wssurl: "",
  tokens: {
    USDT: {
      contract: "",
      name: "Tether",
      symbol: "USDT",
      decimals: 6,
      logo: "usdt.svg",
    },
    USDC: {
      contract: "",
      name: "USDC",
      symbol: "USDC",
      decimals: 6,
      logo: "usdc.svg",
    },
  },
}
chainConfiguration.stellar.networks.mainnet = {
  id: 0,
  name: "Stellar Mainnet",
  slug: "mainnet",
  symbol: "XLM",
  decimals: 6,
  gasprice: "250000000",
  explorer: "https://stellarchain.io",
  rpcUrl: "https://horizon.stellar.org",
  wssurl: "",
  networkPassphrase: "Public Global Stellar Network ; September 2015",
  tokens: {
    USDC: {
      contract: "CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75",
      name: "USDC",
      symbol: "USDC",
      decimals: 6,
      logo: "usdc.svg",
    },
  },
}
chainConfiguration.stellar.networks.testnet = {
  id: 0,
  name: "Stellar Testnet",
  slug: "testnet",
  symbol: "XLM",
  decimals: 6,
  gasprice: "250000000",
  explorer: "https://stellarchain.io",
  rpcUrl: "https://horizon-testnet.stellar.org",
  wssurl: "",
  networkPassphrase: "Test SDF Network ; September 2015",
  tokens: {
    USDC: {
      contract: "CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA",
      name: "USDC",
      symbol: "USDC",
      decimals: 6,
      logo: "usdc.svg",
    },
  },
}
chainConfiguration.stellar.networks.futurenet = {
  id: 0,
  name: "Stellar Futurenet",
  slug: "futurenet",
  symbol: "XLM",
  decimals: 6,
  gasprice: "250000000",
  explorer: "https://stellarchain.io",
  rpcUrl: "https://horizon-futurenet.stellar.org",
  wssurl: "",
  networkPassphrase: "Test SDF Future Network ; October 2022",
}
chainConfiguration.xinfin.networks.mainnet = {
  id: 50,
  name: "XinFin Mainnet",
  slug: "mainnet",
  symbol: "XDC",
  decimals: 18,
  gasprice: "12500000000",
  explorer: "https://explorer.xinfin.network",
  rpcUrl: "https://rpc.xinfin.network",
  wssurl: "",
}
chainConfiguration.xinfin.networks.testnet = {
  id: 51,
  name: "XinFin Testnet",
  slug: "testnet",
  symbol: "XDC",
  decimals: 18,
  gasprice: "12500000000",
  explorer: "https://explorer.apothem.network",
  rpcUrl: "https://rpc.apothem.network",
  wssurl: "",
}
chainConfiguration.xrpl.networks.mainnet = {
  id: 0,
  name: "XRP Mainnet",
  slug: "mainnet",
  symbol: "XRP",
  decimals: 6,
  gasprice: "250000000",
  explorer: "https://etherscan.io",
  rpcUrl: "https://ethereum.publicnode.com",
  wssurl: "",
}
chainConfiguration.xrpl.networks.testnet = {
  id: 0,
  name: "XRP Testnet",
  slug: "testnet",
  symbol: "XRP",
  decimals: 6,
  gasprice: "250000000",
  explorer: "https://goerli.etherscan.io",
  rpcUrl: "https://ethereum-goerli.publicnode.com",
  wssurl: "",
}

export const getChainConfiguration = (slugs: ChainSlugs[]): ChainConfig[] => {
  return slugs.map((slug) => chainConfiguration[slug])
}

export default chainConfiguration
