name: UI Tests

on:
  push:
    branches:
      - dev
      - playwright-testing-draft
  pull_request:
    branches:
      - dev

jobs:
  ui-tests:
    timeout-minutes: 60  # More reasonable timeout (1 hour)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy  # Match version with package.json
      options: --ipc=host --memory=4g --cpus=2  # Add resource limits
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for detecting changed files
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Setup pnpm config
        run: pnpm config set store-dir ~/.pnpm-store
      
      # Add caching for faster builds
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
          
      - name: Install dependencies
        run: pnpm install --filter="./packages/ui-tests" --filter="./packages/ui-tests^..."
          
      - name: Install Playwright browsers
        working-directory: packages/ui-tests
        run: pnpm exec playwright install --with-deps chromium
          
      # Run tests against the Vercel deployment
      - name: Run UI tests
        working-directory: packages/ui-tests
        env:
          PLAYWRIGHT_TEST_BASE_URL: https://give-base-git-kuyawa-partners-login-cfce.vercel.app
          CI: true
          DEBUG: pw:api,pw:browser*  # More detailed Playwright debugging
          PLAYWRIGHT_TIMEOUT: 60000
        run: |
          pnpm test
          
      # Upload test results
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            packages/ui-tests/playwright-report/
            packages/ui-tests/test-results/
          retention-days: 30
          
      # Upload traces on failure
      - name: Upload traces on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: packages/ui-tests/test-results/
          retention-days: 7